services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1135:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
